version: "3.8"

networks:
  preprod:
     external: true  

volumes:
  db-data:
  backend_logs:
     
services:
  db-release:
    image: ${IMAGE_BASE}/release/db:${DB_RELEASE_TAG}
    container_name: db-release
   # entrypoint: ["--config", "/etc/mongod.conf"]
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ADMIN_PASSWD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
      TZ: Europe/Paris
    volumes:
      - db-data:/data/db
      #- ./mongod.conf:/etc/mongod.conf:ro
      #- /etc/localtime:/etc/localtime:ro
    expose:
      - 27017
    ports:
      - 27118:27017
    networks:
      - preprod
  api-release:
    image: ${IMAGE_BASE}/release/api:${API_RELEASE_TAG}
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - MONGO_URI=mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/thetiptop
      - FRONT_END_URL=https://dev.dsp-archiwebo21-ct-df-an-cd.fr
      - APP_URL=https://api.dev.dsp-archiwebo21-ct-df-an-cd.fr

    volumes:
       - /etc/localtime:/etc/localtime:ro
       - backend_logs:/usr/app/error.log
   
    restart: unless-stopped
    container_name: api-release
    depends_on:
      - db-release
    labels:
        - traefik.enable=true
        - traefik.http.routers.api-release.rule=Host(`api.dev.${DOMAIN_BASE}`)
        - traefik.http.routers.api-release.entrypoints=websecure
        - traefik.http.services.api-release.loadbalancer.server.port=3000
    networks:
      - preprod