version: "3.8"

networks:
  preprod:
     external: true  

volumes:
  db-data:
  backend_code:
     

services:
  db-release:
    image: ${IMAGE_BASE}/release/db:${DB_RELEASE_TAG}
    container_name: db-release
    entrypoint: ["mongod", "--auth", "--config", "/etc/mongod.conf"]
    command: "--sslDisabledProtocols 'none'"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
    volumes:
      - db-data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      #- /etc/localtime:/etc/localtime:ro
    expose:
      - 27017
    ports:
      - 27118:27017
    networks:
      - preprod
  api-release:
    image: ${IMAGE_BASE}/release/api:${API_RELEASE_TAG}
    logging:
      driver: gelf
      options:
        gelf-address: udp://${DEVOPS_HOST}:12201
    environment:
      - TZ=Europe/Paris
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - backend_code:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped
    links:
      - db-release:db
    container_name: api-release
    depends_on:
      - db
    labels:
        - traefik.enable=true
        - traefik.http.routers.api-release.rule=Host(`api.dev.${DOMAIN_BASE}`)
        - traefik.http.routers.api-release.entrypoints=websecure
        - traefik.http.services.api-release.loadbalancer.server.port=3000
    networks:
      - preprod