import {
  IsNotEmpty, 
  IsString, 
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CreateTicketDto {

  @ApiProperty({
    example: '1234567890',
    description: ' This is generated by the backend.',
    format: 'string',
  })
  ticketNumber: String;

  @ApiProperty({
    example: '639342b2d71ec7e371800b37',
    description: ' This is generated by the backend.',
    format: 'string',
  })
  idGroup: string;

  @ApiProperty({
    example: '639342b2d71ec7e371800b37',
    description: 'Id of the session where the ticket is part of',
    format: 'string',
  })
  @IsNotEmpty({message: 'l\'id de la session ne peut pas être vide'})
  @IsString({message: 'l\'id de la session doit être une chaîne de caractère'})
  idSession: string;
}
