version: "3.8"

networks:
  api-network:

volumes:
  db-data:

services:
  db:
    image: ${BASE_IMG}/db/dev:${DB_DEV_TAG}
    container_name: db
    volumes:
      - db-data:/data/db
    networks:
      - api-network 
  api:
    image: ${BASE_IMG}/api/dev:${API_DEV_TAG}
    container_name: api
    networks:
      - api-network