version: "3.8"

networks:
  api-network:

volumes:
  db-data:

services:
  db:
    image: ${BASE_IMG}/release/db:${DB_TAG}
    container_name: db
    volumes:
      - db-data:/data/db
    networks:
      - api-network 
  api:
    image: ${BASE_IMG}/release/api:${API_TAG}
    container_name: api
    ports:
      - 80:3000
    networks:
      - api-network