version: "3.8"

networks:
  api-network:

volumes:
  db-data:

services:
  db:
    image: ${BASE_IMG}/db:${DB_DEV_TAG_IMG}
    container_name: db
    volumes:
      - db:data:/data/db
    networks:
      - api-network 
  api:
    image: ${BASE_IMG}/api:${API_DEV_TAG_IMG}
    container_name: api
    networks:
      - api-network