version: "3.8"

networks:
  prod:
     external: true  

volumes:
  db-data:

services:
  db:
    image: ${BASE_IMG}/db:${DB_PROD_TAG_IMG}
    container_name: db
    volumes:
      - db:data:/data/db
    networks:
      - prod 
  api:
    image: ${BASE_IMG}/api:${API_PROD_TAG_IMG}
    labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`api.${DOMAIN_BASE}`)
        - traefik.http.routers.api.middlewares=myAdmin@docker
        - traefik.http.routers.api.entrypoints=websecure
        - traefik.http.routers.api.service=registry-web
        - traefik.http.services.api.loadbalancer.server.port=3000
    container_name: api
    networks:
      - prod